import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>DJ Events</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to DJ Events</h1>

        <p className={styles.description}>Under Construction</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Card &rarr;</h2>

            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores
              quos harum suscipit aliquam mollitia eligendi quibusdam aut
              voluptas nobis! Aliquam!
            </p>
          </div>
          <div className={styles.card}>
            <h2>Card &rarr;</h2>

            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores
              quos harum suscipit aliquam mollitia eligendi quibusdam aut
              voluptas nobis! Aliquam!
            </p>
          </div>
          <div className={styles.card}>
            <h2>Card &rarr;</h2>

            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores
              quos harum suscipit aliquam mollitia eligendi quibusdam aut
              voluptas nobis! Aliquam!
            </p>
          </div>
          <div className={styles.card}>
            <h2>Card &rarr;</h2>

            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores
              quos harum suscipit aliquam mollitia eligendi quibusdam aut
              voluptas nobis! Aliquam!
            </p>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
